### ISSUE TITLE
what is this

### ISSUE THREAD

**Issue by tylenstar** [airysen/abdg#1]
ITERATION #  0

  0%|          | 0/8124 [00:00<?, ?it/s]
 36%|###5      | 2914/8124 [00:00<00:00, 26894.08it/s]
Traceback (most recent call last):
  File "C:\Users\amirj\Documents\Data Mining\Project\abdg-master\abdg-master\examples\example_mushrooms.py", line 58, in <module>
    X_abdg, y_abdg = imput.predict(X.drop('bruises', axis=1), X['bruises'])
  File "C:\Python64\lib\site-packages\abdg\imput.py", line 130, in predict
    sgraph = self.make_subgraph(xi, col)
  File "C:\Python64\lib\site-packages\abdg\imput.py", line 183, in make_subgraph
    edges = self.G.edge[nod]
AttributeError: 'Graph' object has no attribute 'edge'
>>>

**Comment by airysen** [comment]
Hi! I will check this.  It seems like there were changes in latest NetworkX.

**Comment by tylenstar** [comment]
Hi
Ohh..ohkk...i downgraded the networkX...it worked ...great job on your programming...is it possible that can you help me on my class project?



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by mitul6767** [comment]
I am getting keyerror(1) while indexing edge during generation of a subgraph. I have also attached a screenshot. Can you please resolve it? 
here node is like (1,2), (1,3), (0,1)
and edge is like [((1,2), (1,3)), ((1,3), (0,1)),.....]
and the following line of code is giving error as value of nod is (1,2) as INSTANCE.
edges = self.G.edges[nod]
Do I need to chande this index? and if yes than how?
my mail id is mitul6767@gmail.com
<img width="1440" alt="screenshot 2018-11-17 at 1 48 36 pm" src="https://user-images.githubusercontent.com/45128247/48664648-d0ca7a00-ea6f-11e8-8506-9a7226a7a7f9.png">
